# Generated by Django 2.1.7 on 2019-03-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('org', models.CharField(max_length=70, unique=True, verbose_name='org')),
                ('man', models.CharField(blank=True, max_length=50, verbose_name='man')),
                ('theme', models.CharField(blank=True, max_length=250, verbose_name='theme')),
            ],
        ),
    ]
