# Generated by Django 2.1.7 on 2019-04-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('them', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
