# Generated by Django 2.1.7 on 2019-06-03 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpr', '0003_auto_20190530_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpr',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpr',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
