# Generated by Django 2.1.7 on 2019-03-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, verbose_name='username')),
                ('flag', models.BooleanField(default=False, verbose_name='flag')),
                ('timemomenst', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(db_index=True, max_length=100, verbose_name='nazv')),
                ('duration', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namet', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='namet')),
                ('theme', models.CharField(db_index=True, max_length=250, verbose_name='theme')),
                ('leading', models.CharField(max_length=50, verbose_name='lead')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
