# Generated by Django 2.1.7 on 2019-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredpeople',
            name='namesobr',
            field=models.ManyToManyField(to='pril.Collect'),
        ),
    ]
