# Generated by Django 2.1.7 on 2019-05-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0002_auto_20190506_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='name',
            new_name='namec',
        ),
    ]
