# Generated by Django 2.1.7 on 2019-05-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0003_auto_20190506_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='namec',
            new_name='name',
        ),
    ]
