# Generated by Django 2.1.7 on 2019-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0004_auto_20190427_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesobr', models.ManyToManyField(to='pril.Collect')),
            ],
        ),
    ]
