# Generated by Django 2.1.7 on 2019-05-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0004_auto_20190506_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moment',
            old_name='nazv',
            new_name='nazvv',
        ),
    ]
