# Generated by Django 2.1.7 on 2019-04-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0005_requiredpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredpeople',
            name='listeners',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='pril.Collect'),
            preserve_default=False,
        ),
    ]
