# Generated by Django 2.1.7 on 2019-04-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0006_requiredpeople_listeners'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredpeople',
            name='leading',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='leading', to='pril.Collect'),
            preserve_default=False,
        ),
    ]
