# Generated by Django 2.1.7 on 2019-05-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0007_auto_20190506_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='namets',
            new_name='namet',
        ),
    ]
