# Generated by Django 2.1.7 on 2019-04-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0007_requiredpeople_leading'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='lelpeep',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='lelpeep', to='pril.Golos'),
            preserve_default=False,
        ),
    ]
