# Generated by Django 2.1.7 on 2019-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0008_auto_20190506_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='namet',
            field=models.CharField(max_length=250, verbose_name='namet'),
        ),
        migrations.AlterField(
            model_name='template',
            name='theme',
            field=models.CharField(max_length=150, verbose_name='theme'),
        ),
    ]
