# Generated by Django 2.1.7 on 2019-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0009_auto_20190506_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredpeople',
            name='namesobr',
            field=models.ManyToManyField(to='pril.Titempl'),
        ),
        migrations.AlterField(
            model_name='template',
            name='namet',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='namet'),
        ),
        migrations.AlterField(
            model_name='template',
            name='theme',
            field=models.CharField(db_index=True, max_length=250, verbose_name='theme'),
        ),
    ]
