# Generated by Django 2.1.7 on 2019-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0010_auto_20190506_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='namet',
            field=models.CharField(max_length=200, verbose_name='namet'),
        ),
    ]
