# Generated by Django 2.1.7 on 2019-05-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0011_auto_20190506_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golos',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up', to='userpr.Userpr', verbose_name='Связь к таблице'),
        ),
    ]
