# Generated by Django 2.1.7 on 2019-05-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0012_auto_20190507_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vremidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='golos',
            name='username',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='up', to='userpr.Userpr', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pril.Vremidat'),
        ),
    ]
