# Generated by Django 2.1.7 on 2019-05-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0013_auto_20190507_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pril.Vremidat'),
        ),
    ]
