# Generated by Django 2.1.7 on 2019-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0015_remove_collect_peopleincoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='golos',
            name='timemomenst',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
