# Generated by Django 2.1.7 on 2019-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0016_auto_20190530_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
