# Generated by Django 2.1.7 on 2019-05-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0018_auto_20190530_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название собрания'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='org',
            field=models.CharField(max_length=70, unique=True, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='theme',
            field=models.CharField(max_length=250, verbose_name='Тема собрания'),
        ),
    ]
