# Generated by Django 2.1.7 on 2019-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0019_auto_20190530_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoplincollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvsobr', models.CharField(max_length=100, verbose_name='Название собрания')),
                ('user', models.CharField(max_length=100, verbose_name='Человек который будет на собрани')),
            ],
        ),
    ]
