# Generated by Django 2.1.7 on 2019-06-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0021_auto_20190603_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplincollect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpr.Userpr', verbose_name='user'),
        ),
    ]
