# Generated by Django 2.1.7 on 2019-06-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpr', '0004_auto_20190603_1343'),
        ('pril', '0022_auto_20190603_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='id',
        ),
        migrations.AddField(
            model_name='golos',
            name='username',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='up', to='userpr.Userpr', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='name',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='Название собрания'),
        ),
    ]
