# Generated by Django 2.1.7 on 2019-06-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0024_auto_20190603_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flage', models.BooleanField(default=False, verbose_name='Флаг')),
            ],
        ),
        migrations.AddField(
            model_name='collect',
            name='opisan',
            field=models.CharField(default=3, max_length=500, verbose_name='Описание собрания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golos',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='pril.Flag'),
        ),
        migrations.AddField(
            model_name='collect',
            name='flagin',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, related_name='flagin', to='pril.Flag'),
            preserve_default=False,
        ),
    ]
