# Generated by Django 2.1.7 on 2019-06-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0026_auto_20190603_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='tpesobr',
            field=models.CharField(default='Общедоступное', max_length=20, verbose_name='Тип собрания'),
        ),
    ]
