# Generated by Django 2.1.7 on 2019-06-05 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pril', '0027_collect_tpesobr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golos',
            name='username',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='up', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
